# Generated by Django 4.2.3 on 2023-07-16 12:22

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0005_like_delete_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='definition',
            name='likes',
            field=models.ManyToManyField(related_name='definitions', to=settings.AUTH_USER_MODEL),
        ),
    ]
