# Generated by Django 4.2.3 on 2023-07-16 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_definition_likes'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Like',
        ),
    ]
