# Generated by Django 4.2.3 on 2023-07-22 23:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_categories_delete_enrudictionary_delete_phrase'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Categories',
            new_name='Category',
        ),
    ]
