# Generated by Django 4.2.3 on 2023-08-02 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_rename_category_category_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='description',
            field=models.TextField(default='Category description'),
        ),
        migrations.AddField(
            model_name='definition',
            name='categories',
            field=models.ManyToManyField(related_name='definitions', to='blog.category'),
        ),
    ]
