# Generated by Django 4.2.3 on 2023-09-02 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_remove_category_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='definition',
            old_name='word',
            new_name='phrase',
        ),
    ]
